In [13]:
from transformers import AutoTokenizer
# bert_base='./pretrain/bert-base-uncased/'
bert_base = "./pretrain/deberta-v3-large"
bert_tokenizer = AutoTokenizer.from_pretrained(bert_base)

/home/xiongcw/y/envs/temp/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/home/xiongcw/y/envs/temp/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:551: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


BOS is  there a delta          flight from denver              to  san               francisco          EOS	
 O   O  O     O B-airline_name O      O    B-fromloc.city_name O   B-toloc.city_name I-toloc.city_name 
atis_flight


In [16]:
inputs = "[cls] BOS what are the nonstop flights on america west or southwest air from kansas city to burbank on saturday may twenty two EOS"
# inputlit = inputs.split(" ")
# for i in inputlit:
#     token = bert_tokenizer.tokenize(i)
#     print(i,"\t", token)
token = bert_tokenizer.tokenize(inputs)
token

['▁[',
 'cl',
 's',
 ']',
 '▁BOS',
 '▁what',
 '▁are',
 '▁the',
 '▁nonstop',
 '▁flights',
 '▁on',
 '▁america',
 '▁west',
 '▁or',
 '▁southwest',
 '▁air',
 '▁from',
 '▁kansas',
 '▁city',
 '▁to',
 '▁bur',
 'bank',
 '▁on',
 '▁saturday',
 '▁may',
 '▁twenty',
 '▁two',
 '▁EOS']

In [4]:
inputs = "[cls] BOS what are the nonstop flights on america west or southwest air from kansas city to burbank on saturday may twenty two EOS"

lit = [tuple(map(lambda s: s == "B", t )) for t in inputs]
lit

[(False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (True,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),
 (False,),


In [12]:
import torch

a = torch.randint(low = 1,high=10,size = (3,2,4)).float()
b = torch.tensor([-1,-1,-1,-1])

c = a.mean(1)
print(c.shape)
# print(a,"\t", a.shape)
# print(b,"\t",b.shape)
# c = a *b
# print(c, "\t", c.shape)

torch.Size([3, 4])


In [1]:
import torch
from torch import nn
ENV_SEED = 1231
torch.manual_seed(ENV_SEED)

class Model(nn.Module):
    def __init__(self,hidden_dim):
        super(Model,self).__init__()

        self.linear = nn.Linear(hidden_dim, hidden_dim //2)
    
    def forward(self,x):
        x = self.linear(x)

        return x

model = Model(4)
model.cuda()
inputs = torch.randn(size=(2,4))

# output = model(inputs)
print(model.linear.weight.data)


tensor([[-0.1434,  0.3087, -0.2963,  0.0805],
        [ 0.2636,  0.0529, -0.2220, -0.3518]], device='cuda:0')


In [4]:
dic1 = {"wef":2}
dic2 = {"fff":3}

dic1.update(dic2)
print(dic1)

{'wef': 2, 'fff': 3}


In [15]:
from torch import nn
import torch
loss_function_2 = nn.CrossEntropyLoss(reduction="sum")

a = torch.randint(low = 1, high=5, size=(2,3)).float()
b = torch.randint(low=1,high=3, size=(1,2)).view(-1)

print(a)
print(b)

print(loss_function_2(a,b))

tensor([[1., 1., 3.],
        [4., 3., 2.]])
tensor([1, 2])
tensor(4.6472)


In [1]:
import torch
import torch.nn as nn

# 预测分数 (logits)
pred_score = torch.tensor([[2.0, 1.0, 0.1],
                           [0.5, 2.5, 0.3]])

# 目标标签
target = torch.tensor([0, 1])

# 创建 CrossEntropyLoss 实例
criterion = nn.CrossEntropyLoss()

# 计算损失
loss = criterion(pred_score, target)
print(loss.item())  # 输出: 0.318



0.31853973865509033


In [1]:
class A:
    some_attribute = "Hello from class A"

class B(A):
    @classmethod
    def some_class_method(cls):
        # 访问类A中的类属性
        print(cls.some_attribute)

# 调用类方法
B.some_class_method()


Hello from class A


In [3]:
import torch
import torch.nn as nn
from torchcrf import CRF

class CRFModel(nn.Module):
    def __init__(self, num_tags):
        super(CRFModel, self).__init__()
        self.num_tags = num_tags
        self.crf = CRF(num_tags, batch_first=True)

    def forward(self, emissions, tags, mask):
        # 计算 CRF 损失
        loss = -self.crf(emissions, tags, mask=mask)
        return loss

    def decode(self, emissions, mask):
        # 使用 CRF 进行解码
        return self.crf.decode(emissions, mask=mask)

# 示例参数
num_tags = 5
seq_length = 10
batch_size = 2

# 创建模型
model = CRFModel(num_tags)

# 示例输入
emissions = torch.randn(batch_size, seq_length, num_tags)
tags = torch.randint(0, num_tags, (batch_size, seq_length))
mask = torch.ones(batch_size, seq_length, dtype=torch.uint8)

# 计算损失
loss = model(emissions, tags, mask)
print("Loss:", loss.item())

# 解码
decoded_tags = model.decode(emissions, mask)
print("Decoded tags:", decoded_tags)


Loss: 36.556358337402344
Decoded tags: [[4, 0, 1, 1, 0, 1, 3, 2, 0, 1], [4, 0, 0, 2, 0, 2, 1, 3, 0, 0]]


/home/xiongcw/y/envs/temp/lib/python3.9/site-packages/torchcrf/__init__.py:249: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at ../aten/src/ATen/native/TensorCompare.cpp:530.)
  score = torch.where(mask[i].unsqueeze(1), next_score, score)
